FROM mysql:8.0

# Copy initialization SQL script
COPY "DATABASE FILE/attendancesystem.sql" /docker-entrypoint-initdb.d/init.sql

# Set default command
CMD ["--default-authentication-plugin=mysql_native_password"]

